### PR TITLE
Add Maven Wrapper

### LINKED ISSUE #175: Adopt Maven Wrapper
Follow-up to #168 (specifically https://github.com/lastnpe/eclipse-null-eea-augments/pull/168#discussion_r1735960431) to, after merging, add the [Maven Wrapper](https://maven.apache.org/wrapper/) to this project.

I'll do this myself some time when I have a minute. If someone gets to it before me, please just re-assign the issue to yourself.

### PR DESCRIPTION
**Pull request by vorburger**
Fixes #175.

@J-N-K and @sebthom OK for you? Plz Merge if LGTY; thanks!

PS: Ignore the revert commit on this PR ([due to this](https://github.com/lastnpe/eclipse-null-eea-augments/issues/175#issuecomment-2320892697)), I just couldn't figure out how to get rid of it, here.

### CODE REVIEW

**Comment by sebthom** [comment]
just out of interest how is the process in upgrading the wrapper or the maven version? is there e. g. a command that can upgrade both to the latest minor version? If so we could add a ci job to create PRs accordingly.

**Comment by sebthom** [comment]
I saw the build failed because of a commit signing is missing. does the "signed-of-by" commit signing actually have any value? It is not cryptographic anyway. I wouldn't mind to remove it. None of the eclipse projects I am contributing to has it.

**Comment by J-N-K** [comment]
It's a kind of "CLA per commit", see https://wiki.linuxfoundation.org/dco.

**Review by J-N-K — APPROVED** [review]

**Review by sebthom — CHANGES_REQUESTED** [review]
This commit needs to be removed.

**Comment by sebthom** [comment]
I rebased the branch which resolves the issue of the diff showing "0 changed files".

@vorburger Can we merge it without commit sign-off? Btw. the contribution guidelines don't say anything about a requirement for commit signing. Maybe they should be extended and maybe a pull request template should be created that names that requirement.

**Review by sebthom — APPROVED** [review]

**Comment by vorburger** [comment]
> I rebased the branch which resolves the issue of the diff showing "0 changed files".

Thank You!

> just out of interest how is the process in upgrading the wrapper or the maven version? is there e. g. a command that can upgrade both to the latest minor version? If so we could add a custom ci job to create PRs accordingly, since dependabot does not yet support upgrading maven wrapper https://github.com/dependabot/dependabot-core/issues/485 but there is https://github.com/marketplace/actions/update-gradle-wrapper-action

FYI somehow (to my own surprise!) Dependabot actually seem to proposed version bumps upgrades for the Maven Wrapper... see https://github.com/enola-dev/enola/pull/869/files for an example I've just run into!

> does the "signed-of-by" commit message appendix actually have any value? It is not cryptographic anyway. I wouldn't mind to remove it. None of the eclipse projects I am contributing to has it.

Re. ^^^ this is why:

> It's a kind of "CLA per commit", see https://wiki.linuxfoundation.org/dco. IIRC eclipse projects require signing a CLA prior to the first contribution.

> Maybe they should be extended and maybe a pull request template should be created that names that requirement.

Good idea! Do you want to do that? I do think this could avoid hypothetical problems - if this was ever used by more people.

>  Can we merge it without commit sign-off?

I'll fix it.

**Pull request merged**
