### PR TITLE
chore: rename java to java-17

### PR DESCRIPTION
**Pull request by sebthom**
This is in preparation to add a java-21 module.

### CODE REVIEW

**Review by vorburger — APPROVED** [review]
LGTM

**Comment by vorburger** [comment]
PS: I've just noticed that this still says "Travis CI - Pull Request Expected — Waiting for status to be reported", and used this as the opportunity to uninstall it. So that check shouldn't run anymore on the next PR. Perhaps @sebthom re-adding a basic GitHub workflow next would be useful?

**Comment by sebthom** [comment]
my other PR contains some workflows

**Comment by sebthom** [comment]
@vorburger can you check that GitHub Actions are actually enabled for this project?

**Comment by J-N-K** [comment]
image

Seems to be fine

**Pull request merged**
