### PR TITLE
added additional GAVs for JavaMail Message annotation

### PR DESCRIPTION
**Pull request by focbenz**
Added additional GAVs for the JavaMail API that are referenced here: https://javaee.github.io/javamail/
javax.mail:javax.mail-api
com.sun.mail:mailapi

### CODE REVIEW

**Comment by maggu2810** [comment]
Why do you include the changes applied from #64 here, too?

**Comment by focbenz** [comment]
GitHub did not refresh the Pull Request diff for the new  ... let me create a clean follow-up commit from a new branch and pull request: https://github.com/lastnpe/eclipse-null-eea-augments/pull/71
Closing this one

**Comment by maggu2810** [comment]
No need to create a new PR. You only need to rebase your branch

**Comment by focbenz** [comment]
Looks like I did something evil in my fork an force pushed a modified commit.

**Pull request closed without merging**
